name: Lint (pylint)

on:
  push:
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.10', '3.13']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

        # cd backend
      - name: Install dependencies with Poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --no-ansi

      - name: Run pylint
        # working-directory: backend
        # check pylint issues unsubscriptable-object for E1136
        # like that https://github.com/sqlalchemy/sqlalchemy/discussions/9202
        run: |
          source .venv/bin/activate
          FILES=$(git ls-files 'backend//*.py' ':!backend/alembic/' ':!backend/app/tests/' ':!backend/app/schemas/')
          PYTHONPATH=.:backend pylint --disable=E1136,E1102 $FILES
